version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: CAC2024
    environment:
      MYSQL_ROOT_PASSWORD: CAC2024
      MYSQL_DATABASE: jpereyra$Mega-Task
      MYSQL_USER: admin
      MYSQL_PASSWORD: CAC2024
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8090:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
